language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

addons:
  code_climate:
    repo_token: 78ee100adff3457806b7339b8252594fbb81d3d2235257f702fc18a8fd6c4051

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports; fi"
